const CANONICAL_GUN_NAMES: Record<number, string> = {
  1: 'Roman switcher',
  2: 'Addict',
  3: 'Masonic',
  4: 'Cybernor',
  5: 'Slasher',
  6: 'Westside',
  7: 'Sarison',
  8: 'Saint Money',
  9: 'baby pig',
  10: "Banksy's Escape",
  11: 'Lyra gatekeeper',
  12: 'Klegon bolt',
  13: 'proto1',
  14: 'Savage clown',
  15: 'Empire',
  16: 'Baros',
  17: 'zante',
  18: 'Zaru Time runner',
  19: 'Sweet tooth',
  20: 'prickler',
  21: "Punk'd",
  22: 'Pepperoni',
  23: 'Solidus',
  24: 'Gambu',
  25: 'Cardo',
  26: 'Dori',
  27: 'Tash Vail',
  28: 'mini clown',
  29: 'Bluerug',
  30: 'Libertus',
  31: 'Slayer',
  32: 'Fudwiser',
  33: 'Tainter',
  34: 'Wolfgang mk1',
  35: 'Volume one',
  36: 'Frosaint',
  37: 'Old Timer',
  38: 'Taken',
  39: 'PS LA Rome',
  40: 'Proto 2',
  41: 'Zlinger',
  42: 'Cargo',
  43: 'Hellfire',
  44: 'Saru',
  45: 'Sally',
  46: 'Cosy',
  47: 'Proto 3',
  48: 'Moving On',
  49: 'Chromo',
  50: 'Pusia Runner',
  51: 'Garatum',
  52: 'Jacker',
  53: '3 port',
  54: 'The seer',
  55: 'Calamatus',
  56: 'Crug',
  57: 'Vilus',
  58: 'Diamondo',
  59: 'Carson',
  60: 'oneshot',
  61: 'Tabaku',
  62: 'Jammy Ba*tard',
  63: 'Inside',
  64: 'Mac',
  65: 'sint',
  66: 'barato',
  67: 'scrimbar',
  68: 'unknown',
  69: 'Pepe',
  70: 'Beater',
  71: 'dogo',
  72: 'Lander',
  73: 'City Night',
  74: 'Volume 2',
  75: 'Marilas',
  76: 'Decodeus',
  77: 'Glass',
  78: 'Tokyo drip',
  79: 'Flyer',
  80: 'Ethorodox',
  81: 'Mason',
  82: 'Slider',
  83: 'Spikey',
  84: 'Nailer',
  85: 'Within',
  86: 'Buzzer',
  87: 'Clapper',
  88: 'Pointer',
  89: 'Softly',
  90: 'Lazaru',
  91: 'Trinity',
  92: 'Cage',
  93: 'Tri',
  94: 'Clawbot',
  95: 'Undyor',
  96: 'Futeum MK0',
  97: 'Leron',
  98: 'Spinicus',
  99: 'Royal Basil',
  100: 'Heart of Freedom',
  101: 'Connection',
};

export function getCanonicalGunName(tokenId: number): string | null {
  return CANONICAL_GUN_NAMES[tokenId] ?? null;
}

export function resolveGunName(
  tokenId: number,
  metadataName?: string | null
): string {
  const canonicalName = getCanonicalGunName(tokenId);

  if (canonicalName) {
    return canonicalName;
  }

  const trimmedMetadataName = metadataName?.trim() ?? '';
  if (trimmedMetadataName.length > 0) {
    return trimmedMetadataName;
  }

  return canonicalName ?? `Gun #${tokenId}`;
}
